### PR TITLE
Release Sprint 3

### PR DESCRIPTION
**Pull request by trun-g**

### CODE REVIEW

**Review by tuanngo1001 — APPROVED** [review]
Awesome! Good jobs everybody!

**Review by thain-gd — APPROVED** [review]
Sprint 3 is ready to merge!

**Review by tsonga12 — APPROVED** [review]
Looks good, good jobs guysss!

**Comment by trun-g** [comment]
Sprint 3 done!!

**Review by QuocViNguyen — APPROVED** [review]
Cool

**Pull request merged**
