### PR TITLE
Notification bug

### LINKED ISSUE #108: [BUG] The timer doesn't work when screen is off

### PR DESCRIPTION
**Pull request by thain-gd**
- There was no notification when the timer finishes before while locking the screen.
- Only trigger resetting timer when go out of app (not when locks the screen).
- Close #108

### CODE REVIEW

**Review by tuanngo1001 — APPROVED** [review]
Nice

**Review by tuanngo1001 — CHANGES_REQUESTED** [review]
CI not pass

**Comment by thain-gd** [comment]
> CI not pass

CI issue was fixed now.

**Comment by trun-g** [comment]
CI passed. Nice

**Review by trun-g — APPROVED** [review]

**Review by tuanngo1001 — APPROVED** [review]
Noice

**Pull request merged**
